FROM java:7

WORKDIR /root

RUN wget -O /tmp/ddb.tar.gz https://s3-ap-northeast-1.amazonaws.com/dynamodb-local-tokyo/dynamodb_local_latest.tar.gz \
    && tar xfz /tmp/ddb.tar.gz \
    && rm -rf /tmp/*

EXPOSE 8000

CMD ["java", "-Djava.library.path=.", "-jar", "DynamoDBLocal.jar", "-inMemory", "-port", "8000"]
