version: 2

jobs:
  test:
    docker:
      - image: kainjy/practices-of-serverless:test
        auth:
          username: kainjy
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: pytest test.py

workflows:
  version: 2
  test:
    jobs:
      - test
