version: 2

jobs:
  test:
    docker:
      - image: kainjy/practices-of-serverless:test
        auth:
          username: kainjy
          password: $DOCKERHUB_PASSWORD
      - image: kainjy/practices-of-serverless:dynamodb
        name: dynamodb
        auth:
          username: kainjy
          password: $DOCKERHUB_PASSWORD
    working_directory: /code
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
    steps:
      - checkout
      - run: pytest test.py
  deploy:
    docker:
      - image: kainjy/practices-of-serverless:deploy
        auth:
          username: kainjy
          password: $DOCKERHUB_PASSWORD
    working_directory: /code
    steps:
      - checkout
      - run: apex deploy -r $AWS_DEFAULT_REGION
      - run: apex infra init -force-copy
      - run: apex infra apply -auto-approve

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy
